### ISSUE TITLE
How to use it in Quasar?

### ISSUE THREAD

**Issue by paulvanbladel** [CristalT/quasar-icons-generator#1]
Hi,
Thanks a lot for this library.
Could you be so kind to provide some more details on how to use it in quasar.

**Comment by CristalT** [comment]
Hi,
It is not a library, it's a CLI (command line interface). That is, a tool that can help you generating the icons needed to deploy your quasar app on SPA and Cordova platform.
You must use it as a program commanded through the terminal. Please, take a look at README repository file to learn how to install it and generates icons.

**Comment by paulvanbladel** [comment]
@CristalT Sure, I know what a CLI is, don't worry :) I've seen it generated images.
I'll rephrase my question. What's quasar specific on this?
https://quasar-framework.org/components/icons.html
As far as I understand quasar needs an icon-set. In quasar an image and an icon are quite different concepts.
